/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
